### ISSUE TITLE
Terminar relatório do projeto

### ISSUE THREAD

**Issue by ErickGiffoni** [ErickGiffoni/balanca_aerodinamica#5]
### Tasks
- [ ] Fazer o README.md ;
- [ ] Adicionar o manual de uso (README) da nossa solução ao relatório ;
- [ ] Terminar o tópico 7.4.1 - O Processo

O Relatório encontra-se [aqui](https://www.overleaf.com/3127421569cyyhmdwrrhrj) .
